export const statuses = [
    {
      title: 'Light',
      cost: 50,
      posts: [
        'More launchpad projects',
        'More trending data',
        'Full social monitoring system',
        'Last Funds investments',
        'More analyzed projects',
      ],
    },
    {
      title: 'Pro',
      cost: 100,
      posts: [
        'More launchpad projects',
        'More trending data',
        'Full social monitoring system',
        'Last Funds investments',
        'More analyzed projects',
        'ZeroX private fund (Automate trading)',
        'New projects notifications',
      ],
    },
    {
      title: 'Expert',
      cost: 150,
      blur: true,
      posts: [
        'More launchpad projects',
        'More trending data',
        'Full social monitoring system',
        'Last Funds investments',
        'More analyzed projects',
        'ZeroX private fund (Automate trading)',
        'New projects notifications',
        'New projects notifications',
        'New projects notifications',
      ],
    },
    {
      title: 'Guru',
      cost: 200,
      blur: true,
      posts: [
        'More launchpad projects',
        'More trending data',
        'More trending data',
        'Full social monitoring system',
        'Last Funds investments',
        'More analyzed projects',
        'ZeroX private fund (Automate trading)',
        'New projects notifications',
        'New projects notifications',
        'New projects notifications',
      ],
    },
  ];